### ISSUE TITLE
Duplicate bundle identifier for When and RxWhen

### ISSUE THREAD

**Issue by ludovicarnold** [vadymmarkov/When#32]
`When` and `RxWhen` both have the same bundle identifier which prevents using both at the same time. Also, `RxWhen` depends on `When`, which means both are meant to be used at the same time.

![error](https://user-images.githubusercontent.com/16038011/39247108-be2d8438-4898-11e8-96d1-e1fec1e18f6f.png)

Proposed Solution:
Rename the Bundle identifiers for `RxWhen` to RxWhen-iOS, RxWhen-Mac, etc.

**Comment by vadymmarkov** [comment]
Hey @ludovicarnold! I should be fixed https://github.com/vadymmarkov/When/pull/33
