### ISSUE TITLE
WhenRx as an optional dependency?

### ISSUE THREAD

**Issue by timsearle** [vadymmarkov/When#37]
Is there any way to include When as a dependency via Carthage and have it not pull down RxSwift et al? I won't be using that part of the library and it basically introduces a huge overhead to my Cartfile checkouts and builds otherwise.

**Comment by vadymmarkov** [comment]
I don't think it's possible to have optional dependencies with Carthage, but seeing that `RxSwift` helper is pretty tiny I can actually remove it from the source code and put it to the README instead.

**Comment by timsearle** [comment]
Ah that'd be great! I really wanted to use Carthage with this dependency otherwise the source files interfere with my test coverage + the overhead at build time! Thanks!

**Comment by vadymmarkov** [comment]
Ok, the new version is out 😉 https://github.com/vadymmarkov/When/releases/tag/3.1.0

**Comment by timsearle** [comment]
Ah perfect! Nice one :)
