### ISSUE TITLE
Calling 'when' with more than 3 promises

### ISSUE THREAD

**Issue by guilhermearaujo** [vadymmarkov/When#40]
I stumbled upon a case where I need to pass 4 promises to the `when` function, and they all return different types. Therefore I can't use the function that receives an `Array<T>`.

Is there a specific reason to limit the function to 3 promises? Or is it just because it would need to repeat pretty much similar pieces of code for each number of inputs?

**Comment by vadymmarkov** [comment]
There is no specific reason to have a limit of 3 promises. As you said, that's basically because it would need to repeat the code for each number of inputs.
